// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    IconGridiconsFullscreen: typeof import('~icons/gridicons/fullscreen')['default'];
    IconGridiconsFullscreenExit: typeof import('~icons/gridicons/fullscreen-exit')['default'];
    'IconIc:roundClose': typeof import('~icons/ic/round-close')['default'];
    IconIcOutlineCheck: typeof import('~icons/ic/outline-check')['default'];
    IconIcRoundSettings: typeof import('~icons/ic/round-settings')['default'];
    IconLineMdMenuFoldLeft: typeof import('~icons/line-md/menu-fold-left')['default'];
    IconLineMdMenuUnfoldLeft: typeof import('~icons/line-md/menu-unfold-left')['default'];
    IconMdiGithub: typeof import('~icons/mdi/github')['default'];
    IconMdiLightCog: typeof import('~icons/mdi-light/cog')['default'];
    IconMdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default'];
    IconMdiPin: typeof import('~icons/mdi/pin')['default'];
    IconMdiPinOff: typeof import('~icons/mdi/pin-off')['default'];
    IconMdiRefresh: typeof import('~icons/mdi/refresh')['default'];
    IconMdiWechat: typeof import('~icons/mdi/wechat')['default'];
    IconMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default'];
    IconPhCaretDoubleLeftBold: typeof import('~icons/ph/caret-double-left-bold')['default'];
    IconPhCaretDoubleRightBold: typeof import('~icons/ph/caret-double-right-bold')['default'];
    SvgEmptyData: typeof import('./src/components/svg/SvgEmptyData.vue')['default']
    SvgNetworkError: typeof import('./src/components/svg/SvgNetworkError.vue')['default']
    SvgNoPermission: typeof import('./src/components/svg/SvgNoPermission.vue')['default']
    SvgNotFound: typeof import('./src/components/svg/SvgNotFound.vue')['default']
    SvgServiceError: typeof import('./src/components/svg/SvgServiceError.vue')['default']
  }
}

export { }
