// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    NaiveProvider: typeof import('./components/common/NaiveProvider/index.vue')['default']
    NaiveProviderContent: typeof import('./components/common/NaiveProvider/components/NaiveProviderContent.vue')['default']
  }
}

export { }
